### ISSUE TITLE
set-output command deprecated and will be disabled soon

### ISSUE THREAD

**Issue by scottyhq** [jacobtomlinson/gha-anaconda-package-version#10]
<img width="672" alt="Screenshot 2023-01-17 at 9 37 16 AM" src="https://user-images.githubusercontent.com/3924836/212974719-7ed47ea4-6545-4e9b-b04a-cad3c3bad5c5.png">

see also for a solution https://github.com/jacobtomlinson/gha-find-replace/issues/45

**Comment by jacobtomlinson** [comment]
Closed by #16
