### ISSUE TITLE
A release would be good

### ISSUE THREAD

**Issue by consideRatio** [jacobtomlinson/gha-anaconda-package-version#14]
Running into a timeout seems to be the norm rather than the exception in https://github.com/pangeo-bot/dispatcher/actions/workflows/watch-pangeo-notebook-feedstock.yml.

This was mitigated in #11, but its not released yet.

I've opened #12 and #13 to nudge towards a release - could you take it all the way @jacobtomlinson? Note that it would be great if you cut 1.0.0 instead of 0.1.4 or 0.2.0 as then users can pin to v1 instead and rely on nothing breaking to occur until v2 etc.

![image](https://github.com/jacobtomlinson/gha-anaconda-package-version/assets/3837114/0b621ea2-3f69-4e9d-b3a1-af0cb02822fb)

**Comment by jacobtomlinson** [comment]
Just released `0.1.4`

**Comment by consideRatio** [comment]
Thank you @jacobtomlinson!!
