### ISSUE TITLE
API timeouts

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/gha-anaconda-package-version#2]
It seems the API times out occasionally. Need to add some retries. 

Example
https://github.com/dask/dask-docker/runs/354207633

**Comment by scottyhq** [comment]
Have been getting `2023/10/10 17:40:07 Get https://api.anaconda.org/package/conda-forge/distributed/files: net/http: request canceled (Client.Timeout exceeded while awaiting headers)` in logs recently, and made a small adjustment to increase timeout from 2 to 4 seconds rather than retries

**Comment by jacobtomlinson** [comment]
Closed by #17
